from __future__ import annotations

import argparse
from pathlib import Path

PALETTES = {
    "dark": {
        "name": "dark",
        # Surfaces
        "bg": "#262525",
        "bg_alt": "#2B2A2A",
        "bg_panel": "#333138",
        "bg_elevated": "#3D3B42",
        "bg_input": "#2B2A2A",
        "bg_readonly": "#252424",
        "bg_viewer": "#1C1C1C",
        "bg_disabled": "#333138",
        # Text
        "fg": "#FFFFFA",
        "fg_muted": "#BFBFBF",
        "fg_disabled": "#6B6B6B",
        "fg_on_accent": "#FFFFFF",
        "fg_readonly": "#E8E8E3",
        # Borders
        "border": "#3C3C3C",
        "border_strong": "#55535A",
        # Accent (GT red)
        "accent": "#D42622",
        "accent_hover": "#DA2E2A",
        "accent_pressed": "#9B2927",
        "accent_dim": "#8E1E1E",
        # Selection
        "sel": "#8E1E1E",
        "sel_hover": "#9B2927",
        "sel_inactive": "#55535A",
        # Semantic
        "success": "#1E7B4D",
        "warning": "#8F5A08",
        "error": "#8E1E1E",
        # Tooltip
        "tooltip_bg": "#FFFFFA",
        "tooltip_fg": "#262525",
        "tooltip_border": "#9B2927",
        # Link
        "link": "#DA2E2A",
        "link_hover": "#FF6B67",
        # Empty / muted UI chrome
        "empty_label": "#6B6B6B",
        "branch": "#BFBFBF",
        "branch_hover": "#FFFFFA",
    },
    "light": {
        "name": "light",
        # Surfaces
        "bg": "#F0F0F0",
        "bg_alt": "#FFFFFF",
        "bg_panel": "#E4E4E5",
        "bg_elevated": "#D0D0D1",
        "bg_input": "#FFFFFF",
        "bg_readonly": "#F7F7F7",
        "bg_viewer": "#E8E8E8",
        "bg_disabled": "#E4E4E5",
        # Text
        "fg": "#121D19",
        "fg_muted": "#5C5E5D",
        "fg_disabled": "#8A8C8B",
        "fg_on_accent": "#FFFFFF",
        "fg_readonly": "#1A2420",
        # Borders
        "border": "#C9C9C9",
        "border_strong": "#B3B5B4",
        # Accent (blue)
        "accent": "#0061B0",
        "accent_hover": "#1B72C4",
        "accent_pressed": "#003F73",
        "accent_dim": "#0061B0",
        # Selection
        "sel": "#0061B0",
        "sel_hover": "#003F73",
        "sel_inactive": "#B3B5B4",
        # Semantic
        "success": "#1E7B4D",
        "warning": "#8F5A08",
        "error": "#8E1E1E",
        # Tooltip
        "tooltip_bg": "#121D19",
        "tooltip_fg": "#F0F0F0",
        "tooltip_border": "#003F73",
        # Link
        "link": "#0061B0",
        "link_hover": "#1B72C4",
        # Empty / muted UI chrome
        "empty_label": "#8A8C8B",
        "branch": "#5C5E5D",
        "branch_hover": "#121D19",
    },
}

# Shared QSS template — {placeholders} match palette keys
# Double braces {{ }} become literal braces in the output.

TEMPLATE = r"""/* =====================================================
   Generated by generate_qss.py - JeevesGB - do not hand-edit colours.
   Theme: {name}
   Edit PALETTES / TEMPLATE in generate_qss.py and regenerate.
   ===================================================== */

* {{
    font-family: "Segoe UI", Arial, sans-serif;
    font-size: 10pt;
    outline: none;
}}

QMainWindow, QWidget {{
    background-color: {bg};
    color: {fg};
}}

/* ---------------- ToolBar ---------------- */

QToolBar {{
    font-family: Consolas, "Courier New", monospace;
    font-size: 9pt;
    background-color: {bg_panel};
    border: none;
    spacing: 2px;
    padding: 2px 4px;
}}

QToolBar::separator {{
    background-color: {border};
    width: 1px;
    margin: 1px 2px;
}}

QToolBar QLabel {{
    color: {fg_muted};
    padding: 0 4px;
    background: transparent;
}}

QToolBar QComboBox {{
    min-height: 18px;
    min-width: 160px;
}}

QToolBar QCheckBox {{
    spacing: 4px;
    padding: 0 4px;
}}

QToolButton {{
    background-color: transparent;
    color: {fg};
    border: none;
    border-radius: 3px;
    padding: 2px 4px;
}}

QToolButton:hover {{
    background-color: {accent_hover};
    color: {fg_on_accent};
}}

QToolButton:pressed {{
    background-color: {accent_pressed};
    color: {fg_on_accent};
}}

QToolButton:checked {{
    background-color: {accent};
    color: {fg_on_accent};
    border-radius: 3px;
}}

QToolButton:checked:hover {{
    background-color: {accent_hover};
}}

QToolButton:focus {{
    border: 1px solid {accent};
}}

QToolButton::menu-indicator {{
    subcontrol-origin: padding;
    subcontrol-position: bottom right;
    width: 8px;
    height: 8px;
}}

QToolButton:disabled {{
    color: {fg_disabled};
    background-color: transparent;
}}

/* Side rail (objectName="railButton") */
#railButton {{
    border-radius: 6px;
    padding: 4px;
    margin: 1px;
}}

#railButton:checked {{
    background-color: {accent};
    color: {fg_on_accent};
}}

/* ---------------- Buttons ---------------- */

QPushButton {{
    background-color: {accent};
    color: {fg_on_accent};
    border: none;
    border-radius: 3px;
    padding: 3px 10px;
    min-height: 14px;
}}

QPushButton:hover {{
    background-color: {accent_hover};
}}

QPushButton:pressed {{
    background-color: {accent_pressed};
}}

QPushButton:disabled {{
    background-color: {border};
    color: {fg_muted};
}}

QPushButton:focus {{
    border: 1px solid {accent_pressed};
}}

QPushButton:default {{
    font-weight: 600;
}}

QPushButton[class="secondary"] {{
    background-color: transparent;
    border: 1px solid {border_strong};
    color: {fg};
}}

QPushButton[class="secondary"]:hover {{
    border-color: {accent};
    color: {accent};
    background-color: {bg_panel};
}}

QPushButton[class="secondary"]:pressed {{
    background-color: {bg_elevated};
}}

QPushButton[class="secondary"]:disabled {{
    background-color: transparent;
    border-color: {border};
    color: {fg_disabled};
}}

QPushButton[class="success"] {{
    background-color: {success};
    color: {fg_on_accent};
}}

QPushButton[class="warning"] {{
    background-color: {warning};
    color: {fg_on_accent};
}}

QPushButton[class="error"] {{
    background-color: {error};
    color: {fg_on_accent};
}}

QDialogButtonBox QPushButton {{
    min-width: 60px;
    min-height: 24px;
}}

QDialog QPushButton {{
    min-height: 24px;
}}

/* ---------------- Radio / Checkbox ---------------- */

QRadioButton, QCheckBox {{
    spacing: 6px;
    color: {fg};
    background-color: transparent;
}}

QRadioButton::indicator {{
    width: 14px;
    height: 14px;
    border: 1px solid {border_strong};
    border-radius: 7px;
    background-color: {bg_input};
}}

QCheckBox::indicator {{
    width: 14px;
    height: 14px;
    border: 1px solid {border_strong};
    border-radius: 3px;
    background-color: {bg_input};
}}

QRadioButton::indicator:checked, QCheckBox::indicator:checked {{
    background-color: {accent};
    border-color: {accent_pressed};
}}

QRadioButton::indicator:hover, QCheckBox::indicator:hover {{
    border-color: {accent_hover};
}}

QRadioButton:disabled, QCheckBox:disabled {{
    color: {fg_muted};
}}

QRadioButton::indicator:disabled, QCheckBox::indicator:disabled {{
    background-color: {bg};
    border-color: {border};
}}

QRadioButton::indicator:checked:disabled, QCheckBox::indicator:checked:disabled {{
    background-color: {border_strong};
    border-color: {border};
}}

QCheckBox::indicator:indeterminate {{
    background-color: {warning};
    border-color: {warning};
}}

QRadioButton::indicator:focus, QCheckBox::indicator:focus {{
    border: 1px solid {accent};
}}

/* ---------------- Views: Tree / List / Table ---------------- */

QTreeWidget, QTreeView, QListWidget, QListView, QTableView, QTableWidget {{
    background-color: {bg_alt};
    alternate-background-color: {bg_panel};
    color: {fg};
    border: 1px solid {border};
    border-radius: 3px;
    selection-background-color: {sel};
    selection-color: {fg_on_accent};
    gridline-color: {border};
    outline: none;
}}

QTableView, QTableWidget {{
    gridline-color: {border};
}}

QTableCornerButton::section {{
    background-color: {bg_elevated};
    border: none;
    border-right: 1px solid {border_strong};
    border-bottom: 1px solid {border_strong};
}}

QTreeView::item, QListView::item, QTableView::item, QTableWidget::item {{
    padding: 2px;
}}

QTreeView::item:hover, QListView::item:hover, QTableView::item:hover, QTableWidget::item:hover {{
    background-color: {bg_elevated};
}}

QTreeView::item:selected, QListView::item:selected, QTableView::item:selected, QTableWidget::item:selected {{
    background-color: {sel};
    color: {fg_on_accent};
}}

QTreeView::item:selected:hover, QListView::item:selected:hover,
QTableView::item:selected:hover, QTableWidget::item:selected:hover {{
    background-color: {sel_hover};
}}

/* Dim selection when window/panel is inactive */
QTreeView::item:selected:!active,
QListView::item:selected:!active,
QTableView::item:selected:!active,
QTableWidget::item:selected:!active {{
    background-color: {sel_inactive};
    color: {fg};
}}

QTreeView::branch {{
    background-color: transparent;
}}

QTreeView::branch:hover {{
    background-color: {bg_panel};
}}

QTreeView::branch:has-siblings:adjoins-item {{
    border-image: none;
}}

QHeaderView::section {{
    background-color: {bg_elevated};
    color: {fg};
    padding: 4px;
    border: none;
    border-right: 1px solid {border_strong};
    border-bottom: 1px solid {border_strong};
    font-weight: bold;
}}

QHeaderView::section:hover {{
    background-color: {border_strong};
}}

QHeaderView::down-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {fg};
    margin-right: 8px;
}}

QHeaderView::up-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-bottom: 5px solid {fg};
    margin-right: 8px;
}}

QTreeView::branch:has-children:closed {{
    image: none;
    border-image: none;
    width: 0;
    height: 0;
    border-top: 4px solid transparent;
    border-bottom: 4px solid transparent;
    border-left: 5px solid {branch};
    margin: 0 6px;
}}

QTreeView::branch:has-children:open {{
    image: none;
    border-image: none;
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {branch};
    margin: 0 6px;
}}

QTreeView::branch:has-children:closed:hover,
QTreeView::branch:has-children:open:hover {{
    border-left-color: {branch_hover};
    border-top-color: {branch_hover};
}}

/* App-specific named widgets (set objectName in code) */
#treeEmptyLabel {{
    color: {empty_label};
    background: transparent;
    font-size: 11pt;
}}

#filterEdit {{
    padding: 4px 8px;
    min-height: 20px;
}}

#breadcrumb {{
    color: {fg_muted};
    font-size: 9pt;
}}

#previewInfo, #viewerInfo {{
    color: {fg_muted};
}}

#statusLabel {{
    color: {fg};
}}

#inputList {{
    background-color: {bg_alt};
}}

#filelistCombo {{
    min-width: 160px;
}}

/* ---------------- Tabs ---------------- */

QTabWidget::pane {{
    border: 1px solid {border};
    border-radius: 3px;
    background-color: {bg_alt};
}}

QTabBar::tab {{
    background-color: {bg_panel};
    color: {fg};
    padding: 4px 10px;
    margin-right: 1px;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
}}

QTabBar::tab:selected {{
    background-color: {accent};
    color: {fg_on_accent};
    border-bottom: 2px solid {accent_pressed};
}}

QTabBar::tab:hover:selected {{
    background-color: {accent_hover};
}}

QTabBar::tab:hover {{
    background-color: {bg_elevated};
}}

QTabBar::close-button {{
    image: none;
    background-color: transparent;
    border-radius: 2px;
}}

QTabBar::close-button:hover {{
    background-color: {accent_pressed};
}}

/* ---------------- Inputs ---------------- */

QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QDateEdit, QTimeEdit,
QDateTimeEdit, QTextEdit, QPlainTextEdit, QTextBrowser {{
    font-family: Consolas, "Courier New", monospace;
    font-size: 11px;
    background-color: {bg_input};
    color: {fg};
    border: 1px solid {border};
    border-radius: 3px;
    padding: 3px 6px;
    selection-background-color: {accent};
    selection-color: {fg_on_accent};
}}

QLineEdit:hover, QComboBox:hover, QSpinBox:hover, QDoubleSpinBox:hover,
QDateEdit:hover, QTimeEdit:hover, QDateTimeEdit:hover, QTextEdit:hover,
QPlainTextEdit:hover, QTextBrowser:hover {{
    border: 1px solid {border_strong};
}}

QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QDoubleSpinBox:focus,
QDateEdit:focus, QTimeEdit:focus, QDateTimeEdit:focus, QTextEdit:focus,
QPlainTextEdit:focus, QTextBrowser:focus {{
    border: 1px solid {accent};
}}

QLineEdit:disabled, QComboBox:disabled, QSpinBox:disabled,
QDoubleSpinBox:disabled, QDateEdit:disabled, QTimeEdit:disabled,
QDateTimeEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled,
QTextBrowser:disabled {{
    background-color: {bg_disabled};
    color: {fg_muted};
    border: 1px solid {border};
}}

QTextEdit[readOnly="true"], QPlainTextEdit[readOnly="true"], QTextBrowser {{
    background-color: {bg_readonly};
    color: {fg_readonly};
}}

QTextEdit[readOnly="true"]:focus, QPlainTextEdit[readOnly="true"]:focus {{
    border: 1px solid {border_strong};
}}

QLineEdit[state="error"] {{
    border: 1px solid {error};
}}

QLineEdit[state="warning"] {{
    border: 1px solid {warning};
}}

QLineEdit[state="success"] {{
    border: 1px solid {success};
}}

QComboBox::drop-down {{
    border: none;
    width: 18px;
}}

QComboBox::down-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {fg};
}}

QComboBox::down-arrow:disabled {{
    border-top-color: {fg_disabled};
}}

QComboBox QAbstractItemView {{
    background-color: {bg_input};
    color: {fg};
    border: 1px solid {border};
    border-radius: 3px;
    selection-background-color: {accent};
    selection-color: {fg_on_accent};
    outline: none;
    padding: 2px;
}}

QSpinBox::up-button, QDoubleSpinBox::up-button,
QDateEdit::up-button, QTimeEdit::up-button, QDateTimeEdit::up-button {{
    subcontrol-origin: border;
    subcontrol-position: top right;
    width: 14px;
    border-left: 1px solid {border};
    border-top-right-radius: 3px;
    background-color: {bg_panel};
}}

QSpinBox::down-button, QDoubleSpinBox::down-button,
QDateEdit::down-button, QTimeEdit::down-button, QDateTimeEdit::down-button {{
    subcontrol-origin: border;
    subcontrol-position: bottom right;
    width: 14px;
    border-left: 1px solid {border};
    border-bottom-right-radius: 3px;
    background-color: {bg_panel};
}}

QSpinBox::up-button:hover, QSpinBox::down-button:hover,
QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover,
QDateEdit::up-button:hover, QDateEdit::down-button:hover,
QTimeEdit::up-button:hover, QTimeEdit::down-button:hover,
QDateTimeEdit::up-button:hover, QDateTimeEdit::down-button:hover {{
    background-color: {accent_hover};
}}

QSpinBox::up-arrow, QDoubleSpinBox::up-arrow,
QDateEdit::up-arrow, QTimeEdit::up-arrow, QDateTimeEdit::up-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 3px solid transparent;
    border-right: 3px solid transparent;
    border-bottom: 4px solid {fg};
}}

QSpinBox::down-arrow, QDoubleSpinBox::down-arrow,
QDateEdit::down-arrow, QTimeEdit::down-arrow, QDateTimeEdit::down-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-left: 3px solid transparent;
    border-right: 3px solid transparent;
    border-top: 4px solid {fg};
}}

/* ---------------- Calendar ---------------- */

QCalendarWidget QWidget {{
    background-color: {bg_input};
    color: {fg};
}}

QCalendarWidget QToolButton {{
    background-color: transparent;
    color: {fg};
    padding: 3px 6px;
}}

QCalendarWidget QToolButton:hover {{
    background-color: {accent_hover};
    color: {fg_on_accent};
}}

QCalendarWidget QMenu {{
    background-color: {bg_input};
    color: {fg};
}}

QCalendarWidget QAbstractItemView:enabled {{
    background-color: {bg_input};
    color: {fg};
    selection-background-color: {accent};
    selection-color: {fg_on_accent};
}}

QCalendarWidget QAbstractItemView:disabled {{
    color: {fg_muted};
}}

QCalendarWidget QWidget#qt_calendar_navigationbar {{
    background-color: {bg_panel};
}}

/* ---------------- ScrollArea / Viewer ---------------- */

QScrollArea {{
    background-color: {bg};
    border: 1px solid {border};
    border-radius: 3px;
}}

QScrollArea > QWidget > QWidget {{
    background-color: transparent;
}}

QAbstractScrollArea::corner {{
    background-color: {bg_panel};
    border: none;
}}

#viewerScroll {{
    border: 1px solid {border};
    border-radius: 3px;
}}

#viewerLabel {{
    background-color: {bg_viewer};
}}

/* ---------------- GroupBox ---------------- */

QGroupBox {{
    border: 1px solid {border};
    border-radius: 6px;
    margin-top: 8px;
    padding: 8px;
    color: {fg};
    font-weight: bold;
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    left: 8px;
    padding: 0 4px;
    background-color: {bg};
    color: {accent};
}}

/* ---------------- Menu / MenuBar ---------------- */

QMenuBar {{
    background-color: {bg_panel};
    color: {fg};
}}

QMenuBar::item {{
    background-color: transparent;
    padding: 4px 10px;
}}

QMenuBar::item:selected {{
    background-color: {accent};
    color: {fg_on_accent};
    border-radius: 3px;
}}

QMenu {{
    background-color: {bg_input};
    color: {fg};
    border: 1px solid {border};
    border-radius: 6px;
    padding: 3px;
}}

QMenu::item {{
    padding: 4px 20px 4px 10px;
    border-radius: 3px;
}}

QMenu::item:selected {{
    background-color: {accent};
    color: {fg_on_accent};
}}

QMenu::item:disabled {{
    color: {fg_muted};
}}

QMenu::separator {{
    height: 1px;
    background-color: {border};
    margin: 3px 6px;
}}

QMenu::right-arrow {{
    image: none;
    width: 0;
    height: 0;
    border-top: 4px solid transparent;
    border-bottom: 4px solid transparent;
    border-left: 5px solid {fg};
    margin-right: 4px;
}}

QMenu::right-arrow:selected {{
    border-left-color: {fg_on_accent};
}}

/* ---------------- Dialog / MessageBox ---------------- */

QDialog {{
    background-color: {bg};
    color: {fg};
}}

QMessageBox {{
    background-color: {bg};
}}

QMessageBox QLabel {{
    color: {fg};
}}

/* Setup / help titles (set objectName or class in code) */
#dialogTitle {{
    font-size: 16px;
    font-weight: 600;
    color: {fg};
}}

#dialogSubtitle,
QLabel[class="muted"] {{
    color: {fg_muted};
}}

/* Links in labels / help browser */
QLabel a, QTextBrowser a {{
    color: {link};
    text-decoration: none;
}}

QLabel a:hover, QTextBrowser a:hover {{
    color: {link_hover};
}}

/* ---------------- DockWidget ---------------- */

QDockWidget {{
    color: {fg};
    titlebar-close-icon: none;
    titlebar-normal-icon: none;
}}

QDockWidget::title {{
    background-color: {bg_elevated};
    padding: 4px 6px;
    border: 1px solid {border_strong};
    border-bottom: none;
}}

QDockWidget::close-button, QDockWidget::float-button {{
    background-color: transparent;
    border: none;
    border-radius: 2px;
    padding: 2px;
}}

QDockWidget::close-button:hover, QDockWidget::float-button:hover {{
    background-color: {accent_hover};
}}

/* ---------------- Slider ---------------- */

QSlider::groove:horizontal {{
    height: 4px;
    background: {border};
    border-radius: 2px;
}}

QSlider::sub-page:horizontal {{
    background: {accent};
    border-radius: 2px;
}}

QSlider::handle:horizontal {{
    background: {accent};
    width: 12px;
    height: 12px;
    margin: -5px 0;
    border-radius: 6px;
}}

QSlider::handle:horizontal:hover {{
    background: {accent_hover};
}}

QSlider::handle:horizontal:pressed {{
    background: {accent_pressed};
}}

/* ---------------- Splitter ---------------- */

QSplitter::handle {{
    background-color: {border};
}}

QSplitter::handle:hover {{
    background-color: {accent};
}}

QSplitter::handle:horizontal {{
    width: 3px;
}}

QSplitter::handle:vertical {{
    height: 3px;
}}

/* ---------------- ScrollBar ---------------- */

QScrollBar:vertical {{
    background: {bg_panel};
    width: 10px;
    margin: 0;
    border-radius: 3px;
}}

QScrollBar::handle:vertical {{
    background: {accent};
    border-radius: 4px;
    min-height: 26px;
}}

QScrollBar::handle:vertical:hover {{
    background: {accent_hover};
}}

QScrollBar::handle:vertical:pressed {{
    background: {accent_pressed};
}}

QScrollBar:horizontal {{
    background: {bg_panel};
    height: 10px;
    margin: 0;
    border-radius: 3px;
}}

QScrollBar::handle:horizontal {{
    background: {accent};
    border-radius: 4px;
    min-height: 26px;
}}

QScrollBar::handle:horizontal:hover {{
    background: {accent_hover};
}}

QScrollBar::handle:horizontal:pressed {{
    background: {accent_pressed};
}}

QScrollBar::add-line, QScrollBar::sub-line {{
    width: 0;
    height: 0;
}}

/* ---------------- StatusBar ---------------- */

QStatusBar {{
    background-color: {bg_panel};
    color: {fg};
}}

QStatusBar::item {{
    border: none;
}}

QStatusBar QLabel {{
    color: {fg};
    background: transparent;
}}

/* ---------------- ProgressBar ---------------- */

QProgressBar {{
    border: 1px solid {border};
    border-radius: 3px;
    text-align: center;
    background-color: {bg_panel};
    color: {fg};
    min-height: 14px;
}}

QProgressBar::chunk {{
    background-color: {accent};
    border-radius: 3px;
}}

QProgressBar[busy="true"]::chunk {{
    background-color: {accent_hover};
}}

/* ---------------- ToolTip ---------------- */

QToolTip {{
    background-color: {tooltip_bg};
    color: {tooltip_fg};
    border: 1px solid {tooltip_border};
    border-radius: 3px;
    padding: 3px 6px;
}}

/* ---------------- Label ---------------- */

QLabel {{
    color: {fg};
}}

QLabel:disabled {{
    color: {fg_muted};
}}

QLabel[class="success"] {{ color: {success}; }}
QLabel[class="warning"] {{ color: {warning}; }}
QLabel[class="error"]   {{ color: {error}; }}
"""


def render(theme: str) -> str:
    if theme not in PALETTES:
        raise KeyError(f"Unknown theme {theme!r}; choose from {list(PALETTES)}")
    return TEMPLATE.format(**PALETTES[theme])


def write_themes(out_dir: Path) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for theme in ("light", "dark"):
        path = out_dir / f"{theme}.qss"
        path.write_text(render(theme), encoding="utf-8")
        written.append(path)
    return written


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate light/dark QSS themes")
    ap.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Output directory (default: ./thm next to this script, else cwd/thm)",
    )
    ap.add_argument(
        "--print",
        choices=("light", "dark"),
        dest="print_theme",
        help="Print one theme to stdout instead of writing files",
    )
    args = ap.parse_args()

    if args.print_theme:
        print(render(args.print_theme), end="")
        return

    script_dir = Path(__file__).resolve().parent
    out = args.out
    if out is None:
        for candidate in (
            script_dir / "thm",
            script_dir / "src" / "thm",
            Path.cwd() / "src" / "thm",
            Path.cwd() / "thm",
        ):
            if candidate.is_dir() or (candidate.parent / "src").is_dir():
                out = candidate if candidate.name == "thm" else candidate
                break
        if out is None:
            out = script_dir / "thm"

    paths = write_themes(out)
    for p in paths:
        print(f"Wrote {p} ({p.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
